# Generated by Django 4.0.5 on 2022-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_meeting_name_rename_title_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_repeated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='verify_id',
            field=models.IntegerField(null=True),
        ),
    ]
