# Generated by Django 4.0.5 on 2022-07-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_meeting_options_alter_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
