# Generated by Django 4.0.5 on 2022-07-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meeting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
