# Generated by Django 4.0.5 on 2022-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('d', 'Declined'), ('a', 'Accepted')], default='p', help_text='Meeting status', max_length=1),
        ),
    ]
