# Generated by Django 4.0.5 on 2022-07-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_meeting_options_meeting_created_at_and_more'),
        ('api', '0010_alter_room_id'),
    ]

    operations = [
    ]
