# Generated by Django 4.0.5 on 2022-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20220721_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='is_repeated',
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('c', 'Class'), ('e', 'Event')], default='e', max_length=1),
        ),
    ]
