# Generated by Django 4.0.5 on 2022-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_meeting_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='verify_id',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='pending', help_text='Meeting status', max_length=8),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('class', 'Class'), ('event', 'Event')], default='event', max_length=5),
        ),
    ]
