# Generated by Django 4.0.5 on 2022-07-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_meeting_status'),
        ('api', '0015_rename_name_meeting_title'),
    ]

    operations = [
    ]
