# Generated by Django 4.0.5 on 2022-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20220723_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='pending', help_text='Meeting status', max_length=8),
        ),
    ]
