# Generated by Django 4.0.5 on 2022-07-27 14:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileApload', models.FileField(upload_to=api.models.filePath)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
