# Generated by Django 4.0.5 on 2022-08-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_targetmailuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='academic',
            field=models.BooleanField(default=False),
        ),
    ]
